/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTechRouteImport } from './routes/_authenticated/tech'
import { Route as AuthenticatedTechJobIdRouteImport } from './routes/_authenticated/tech.$jobId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTechRoute = AuthenticatedTechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechJobIdRoute = AuthenticatedTechJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AuthenticatedTechRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tech': typeof AuthenticatedTechRouteWithChildren
  '/tech/$jobId': typeof AuthenticatedTechJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tech': typeof AuthenticatedTechRouteWithChildren
  '/tech/$jobId': typeof AuthenticatedTechJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/tech': typeof AuthenticatedTechRouteWithChildren
  '/_authenticated/tech/$jobId': typeof AuthenticatedTechJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/tech' | '/tech/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/tech' | '/tech/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/tech'
    | '/_authenticated/tech/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tech': {
      id: '/_authenticated/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof AuthenticatedTechRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tech/$jobId': {
      id: '/_authenticated/tech/$jobId'
      path: '/$jobId'
      fullPath: '/tech/$jobId'
      preLoaderRoute: typeof AuthenticatedTechJobIdRouteImport
      parentRoute: typeof AuthenticatedTechRoute
    }
  }
}

interface AuthenticatedTechRouteChildren {
  AuthenticatedTechJobIdRoute: typeof AuthenticatedTechJobIdRoute
}

const AuthenticatedTechRouteChildren: AuthenticatedTechRouteChildren = {
  AuthenticatedTechJobIdRoute: AuthenticatedTechJobIdRoute,
}

const AuthenticatedTechRouteWithChildren =
  AuthenticatedTechRoute._addFileChildren(AuthenticatedTechRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTechRoute: typeof AuthenticatedTechRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTechRoute: AuthenticatedTechRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
